Module 3
waormd/DevOps-Course-Starter pull request #3
Opened 2020-08-11 20:49 UTC by waormd

Added rudimental test for each category

2020-08-24 12:55 UTC, hugh-emerson requested changes
Almost there - some changes to the selenium test are needed, and the README needs updating. See my other comments for details.

2020-08-24 12:55 UTC, hugh-emerson commented on app.py
> +    with open('config/secrets.yml') as file:
First of all, it's not documented, so a developer has to read the code to work out what's required to run the app.

Secondly, you are using both environment variables and a secret config yaml file. Why not stick to environment variables?

2020-08-24 12:55 UTC, hugh-emerson commented on geckodriver.log
> +1596470288014	geckodriver	INFO	Listening on 127.0.0.1:53183
This file should be in .gitignore (You'll have to delete it first because it's already being tracked)

2020-08-24 12:55 UTC, hugh-emerson commented on tests_e2e/test_selenium.py
> +    with webdriver.Firefox(executable_path='C:\\tools\\selenium\\drivers\\geckodriver.exe') as driver:
You shouldn't require everyone to have geckodriver in the same place on their machines. You can actually just call webdriver.Firefox() if geckodriver is either on your PATH or in this project's directory (you should gitignore it if you do include it in the project directory).

Plus the README needs to be updated to include prerequisites for the tests like Firefox and geckodriver.exe, and instructions on how to run the tests.

2020-08-24 12:55 UTC, hugh-emerson commented on todo/view.py
> +        return [ x for x in self._items if x.status == 'Todo' ]
The README should mention that the trello board needs to have "Todo" "In progress" and "Done" lists.

2020-08-24 12:55 UTC, hugh-emerson commented on app.py
> +TRELLO_BOARD_ID = os.getenv('TRELLO_BOARD_ID')
TRELLO_BOARD_ID should be in .env.template and the README should mention that you need to set a value for it in .env.

2020-08-24 12:55 UTC, hugh-emerson commented on geckodriver.log
> +1596470288014	geckodriver	INFO	Listening on 127.0.0.1:53183
Also, tests_e2e/requirements.txt and tests_e2e/geckodriver.log should be deleted.

2020-08-24 12:55 UTC, hugh-emerson commented on tests_e2e/test_selenium.py
> +    assert driver.title == 'To-Do App'
Can you extend this test as per the exercise brief? It should at least create a todo item and verify that it appears.

2020-08-24 12:55 UTC, hugh-emerson commented on tests_e2e/test_selenium.py
> +    os.environ['TRELLO_BOARD_ID'] = board_id
This isn't actually overriding anything.
app.py defines a variable `TRELLO_BOARD_ID = ...` when the file is first imported, way before you reach this line. At no point do you change the value of `TRELLO_BOARD_ID`.

So currently the test is loading the real board, if you run it from vscode which loads .env automatically. Or if you run pytest from command line, the test fails.

2020-08-26 15:08 UTC, waormd commented on tests_e2e/test_selenium.py
> +    os.environ['TRELLO_BOARD_ID'] = board_id
f076e63

2020-08-26 15:09 UTC, waormd commented on tests_e2e/test_selenium.py
> +    assert driver.title == 'To-Do App'
aad3908

2020-08-26 15:09 UTC, waormd commented on app.py
> +TRELLO_BOARD_ID = os.getenv('TRELLO_BOARD_ID')
f076e63

2020-08-26 15:09 UTC, waormd commented on todo/view.py
> +        return [ x for x in self._items if x.status == 'Todo' ]
f076e63

2020-08-26 15:09 UTC, waormd commented on tests_e2e/test_selenium.py
> +    with webdriver.Firefox(executable_path='C:\\tools\\selenium\\drivers\\geckodriver.exe') as driver:
f076e63

2020-08-26 15:09 UTC, waormd commented on app.py
> +    with open('config/secrets.yml') as file:
f076e63

2020-08-26 15:10 UTC, waormd commented on geckodriver.log
> +1596470288014	geckodriver	INFO	Listening on 127.0.0.1:53183
f076e63 
1b87d0d

2020-08-26 19:26 UTC, hugh-emerson approved these changes
Looks good. I've left some small comments but go ahead and merge when you're ready.

It looks like I may have already approved your module 3 submission in Aptem because I mistook it for module 4...

Can you resubmit module 4 in Aptem so that I can approve it?

2020-08-26 19:26 UTC, hugh-emerson commented on tests_e2e/test_selenium.py
> +    submit = driver.find_element(By.XPATH, '/html/body/div/div[2]/div/form/input[2]')
This test would be more robust if it found the element by a class, say, rather than relying on the page structure like this.

Same for finding the card

2020-08-26 19:26 UTC, hugh-emerson commented on tests_e2e/test_selenium.py
> +def test_app():
This test passes from vscode but not from command line (because vscode automatically loads .env)

So it would be nicer to add in
```
    file_path = dotenv.find_dotenv('.env')
    dotenv.load_dotenv(file_path, override=True)
```

2020-08-27 08:55 UTC, merged